
import { useGoogleSheets } from './useGoogleSheets';

// Temporary mock data for testing drill-down functionality
const mockSalesData = [
  // 6 Month Unlimited membership transactions
  {
    memberId: 'M001',
    customerName: 'John Smith',
    customerEmail: 'john@example.com',
    saleItemId: 'S001',
    paymentCategory: 'Membership',
    membershipType: '6 Month Unlimited',
    paymentDate: '12/11/2024',
    paymentValue: 25000,
    paidInMoneyCredits: 0,
    paymentVAT: 4500,
    paymentItem: '6 Month Unlimited',
    paymentStatus: 'Paid',
    paymentMethod: 'Credit Card',
    paymentTransactionId: 'TX001',
    stripeToken: 'tok_001',
    soldBy: 'Anisha Shah',
    saleReference: 'REF001',
    calculatedLocation: 'Kwality House, Kemps Corner',
    cleanedProduct: '6 Month Unlimited',
    cleanedCategory: 'Unlimited Memberships',
    netRevenue: 20500,
    vat: 4500,
    grossRevenue: 25000
  },
  {
    memberId: 'M002',
    customerName: 'Sarah Williams',
    customerEmail: 'sarah@example.com',
    saleItemId: 'S002',
    paymentCategory: 'Membership',
    membershipType: '6 Month Unlimited',
    paymentDate: '11/11/2024',
    paymentValue: 25000,
    paidInMoneyCredits: 0,
    paymentVAT: 4500,
    paymentItem: '6 Month Unlimited',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    paymentTransactionId: 'TX002',
    stripeToken: 'tok_002',
    soldBy: 'Priya Patel',
    saleReference: 'REF002',
    calculatedLocation: 'Supreme HQ, Bandra',
    cleanedProduct: '6 Month Unlimited',
    cleanedCategory: 'Unlimited Memberships',
    netRevenue: 20500,
    vat: 4500,
    grossRevenue: 25000
  },
  {
    memberId: 'M003',
    customerName: 'Mike Johnson',
    customerEmail: 'mike@example.com',
    saleItemId: 'S003',
    paymentCategory: 'Membership',
    membershipType: '6 Month Unlimited',
    paymentDate: '10/11/2024',
    paymentValue: 25000,
    paidInMoneyCredits: 0,
    paymentVAT: 4500,
    paymentItem: '6 Month Unlimited',
    paymentStatus: 'Paid',
    paymentMethod: 'Credit Card',
    paymentTransactionId: 'TX003',
    stripeToken: 'tok_003',
    soldBy: 'Anisha Shah',
    saleReference: 'REF003',
    calculatedLocation: 'Kwality House, Kemps Corner',
    cleanedProduct: '6 Month Unlimited',
    cleanedCategory: 'Unlimited Memberships',
    netRevenue: 20500,
    vat: 4500,
    grossRevenue: 25000
  },
  // Single Session transactions
  {
    memberId: 'M004',
    customerName: 'Emma Davis',
    customerEmail: 'emma@example.com',
    saleItemId: 'S004',
    paymentCategory: 'Single Session',
    membershipType: 'Single Session',
    paymentDate: '12/11/2024',
    paymentValue: 1200,
    paidInMoneyCredits: 0,
    paymentVAT: 216,
    paymentItem: 'Single Session',
    paymentStatus: 'Paid',
    paymentMethod: 'Cash',
    paymentTransactionId: 'TX004',
    stripeToken: 'tok_004',
    soldBy: 'Maya Singh',
    saleReference: 'REF004',
    calculatedLocation: 'Kenkere House',
    cleanedProduct: 'Single Session',
    cleanedCategory: 'Drop-in Classes',
    netRevenue: 984,
    vat: 216,
    grossRevenue: 1200
  },
  {
    memberId: 'M005',
    customerName: 'Alex Brown',
    customerEmail: 'alex@example.com',
    saleItemId: 'S005',
    paymentCategory: 'Single Session',
    membershipType: 'Single Session',
    paymentDate: '11/11/2024',
    paymentValue: 1200,
    paidInMoneyCredits: 0,
    paymentVAT: 216,
    paymentItem: 'Single Session',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    paymentTransactionId: 'TX005',
    stripeToken: 'tok_005',
    soldBy: 'Ravi Kumar',
    saleReference: 'REF005',
    calculatedLocation: 'Supreme HQ, Bandra',
    cleanedProduct: 'Single Session',
    cleanedCategory: 'Drop-in Classes',
    netRevenue: 984,
    vat: 216,
    grossRevenue: 1200
  },
  // 3 Month Unlimited memberships
  {
    memberId: 'M006',
    customerName: 'Lisa Wilson',
    customerEmail: 'lisa@example.com',
    saleItemId: 'S006',
    paymentCategory: 'Membership',
    membershipType: '3 Month Unlimited',
    paymentDate: '10/11/2024',
    paymentValue: 15000,
    paidInMoneyCredits: 0,
    paymentVAT: 2700,
    paymentItem: '3 Month Unlimited',
    paymentStatus: 'Paid',
    paymentMethod: 'Credit Card',
    paymentTransactionId: 'TX006',
    stripeToken: 'tok_006',
    soldBy: 'Anisha Shah',
    saleReference: 'REF006',
    calculatedLocation: 'Kwality House, Kemps Corner',
    cleanedProduct: '3 Month Unlimited',
    cleanedCategory: 'Unlimited Memberships',
    netRevenue: 12300,
    vat: 2700,
    grossRevenue: 15000
  },
  {
    memberId: 'M007',
    customerName: 'David Taylor',
    customerEmail: 'david@example.com',
    saleItemId: 'S007',
    paymentCategory: 'Membership',
    membershipType: '3 Month Unlimited',
    paymentDate: '09/11/2024',
    paymentValue: 15000,
    paidInMoneyCredits: 0,
    paymentVAT: 2700,
    paymentItem: '3 Month Unlimited',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    paymentTransactionId: 'TX007',
    stripeToken: 'tok_007',
    soldBy: 'Priya Patel',
    saleReference: 'REF007',
    calculatedLocation: 'Supreme HQ, Bandra',
    cleanedProduct: '3 Month Unlimited',
    cleanedCategory: 'Unlimited Memberships',
    netRevenue: 12300,
    vat: 2700,
    grossRevenue: 15000
  }
];

export const useSalesData = () => {
  // Temporarily return mock data for testing
  return {
    data: mockSalesData,
    loading: false,
    error: null,
    isLoading: false
  };
  
  // Original Google Sheets integration (commented out for testing)
  // const { data, loading, error } = useGoogleSheets();
  // return {
  //   data,
  //   loading,
  //   error,
  //   isLoading: loading
  // };
};
